[tool.poetry]
name = "pytest-arch"
version = "0.1.0"
description = ""
authors = ["Niko Wilbert <niko.wilbert@tngtech.com>"]
classifiers = ["Framework :: Pytest"]
packages = [
    { include = "pyarch", from = "src" },
]

[tool.poetry.plugins."pytest11"]
arch = "pyarch.pytest_plugin"

[tool.poetry.dependencies]
python = "^3.10"
pytest = "^7.1.2"

[tool.poetry.dev-dependencies]
nox = "^2022.8.7"
nox-poetry = "^1.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
line_length = 79

